server:
  port: 8000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: cambio-service
  datasource:
    driverClassName: org.postgresql.Driver
    platform: postgres
    url: jdbc:postgresql://localhost:5432/cambio-service
    username: postgres
    password: postgres
  jpa:
    show-sql: true
  flyway:
    datasources:
      default:
        enabled: true
        clean-schema: true # faz o create-drop
springdoc:
  show-actuator: true
  api-docs:
    path: cambio-service/v3/api-docs

