version: '3.4'

services: 
  naming-server:
    image : hugovallada/eureka-naming-server:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
    networks: 
      - hugo-network

  api-gateway:
    image: hugovallada/api-gateway:0.0.1-SNAPSHOT
    ports:
     - 8765:8765
    depends_on: 
      - naming-server
    environment: 
      SPRING.ZIPKIN.BASEURL: http://zipkin:9411/
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
    networks: 
      - hugo-network

  cambio-service:
    image: hugovallada/cambio-service
    restart: always
    build:
      context: .
      dockerfile: cambio-service/Dockerfile
    environment: 
      TZ: America/Sao_Paulo
      SPRING.ZIPKIN.BASEURL: http://zipkin:9411/
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.APPLICATION.NAME: cambio-service
      SPRING.DATASOURCE.URL: jdbc:postgresql://cambio-db:5433/cambio_service?useSSL=false&enabledTLSProtocols=TLSv1.2
      SPRING.DATASOURCE.USERNAME: postgres
      SPRING.DATASOURCE.PASSWORD: postgres 
    ports:
      - 8000:8000
    depends_on: 
      - naming-server
      - cambio-db
    networks: 
      - hugo-network

  book-service:
    image: hugovallada/book-service
    restart: always
    build:
      context: .
      dockerfile: book-service/Dockerfile
    environment: 
      TZ: America/Sao_Paulo
      SPRING.ZIPKIN.BASEURL: http://zipkin:9411/
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.APPLICATION.NAME: book-service
      SPRING.DATASOURCE.URL: jdbc:postgresql://book-db:5432/book_service?useSSL=false&enabledTLSProtocols=TLSv1.2
      SPRING.DATASOURCE.USERNAME: postgres
      SPRING.DATASOURCE.PASSWORD: postgres 
    ports:
      - 8100:8100
    depends_on: 
      - naming-server
      - book-db
    networks: 
      - hugo-network

  zipkin:
    image: openzipkin/zipkin:2.23.2
    ports:
      - 9411:9411
    networks: 
      - hugo-network

  cambio-db:
    image: postgres:10.4
    restart: always
    environment: 
      POSTGRES_DB: book_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: America/Sao_Paulo
      POSTGRES_TCP_PORT: 5433
      POSTGRES_HOST: postgres
    ports: 
      - 5433:5433
    expose: 
      - 5433
    networks: 
      - hugo-network

  book-db:
    image: postgres:10.4
    restart: always
    environment: 
      POSTGRES_DB: book_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: America/Sao_Paulo
      POSTGRES_TCP_PORT: 5432
      POSTGRES_HOST: postgres
    ports: 
      - 5432:5432
    expose: 
      - 5432
    networks: 
      - hugo-network
    

networks:
  hugo-network:
    driver: bridge