version: '3.4'

services: 
  naming-server:
    image : hugovallada/eureka-naming-server:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
    networks: 
      - hugo-network

  api-gateway:
    image: hugovallada/api-gateway:0.0.1-SNAPSHOT
    ports:
     - 8765:8765
    depends_on: 
      - naming-server
    environment: 
      SPRING.ZIPKIN.BASEURL: http://zipkin:9411/
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
    networks: 
      - hugo-network

  zipkin:
    image: openzipkin/zipkin:2.23.2
    ports:
      - 9411:9411
    networks: 
      - hugo-network

  cambio-db:
    image: mysql:5.7.22
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: cambio_service
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3306
    ports: 
      - 3306:3306
    expose:
      - 3306
    networks: 
      - hugo-network

  book-db:
    image: mysql:5.7.22
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: book_service
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports: 
      - 3308:3308
    expose:
      - 3308
    networks: 
      - hugo-network
    

networks:
  hugo-network:
    driver: bridge