server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhosT:8761/eureka
spring:
  application:
    name: api-gateway
#  cloud: Não é mais necessário qnd usa o router
#    gateway:
#      discovery:
#        locator:
#          enabled: true # permite q ao invés de usar o localhost do próprio serviço para acessar, usa o próprio api gateway e passa o nome do serviço
#          lower-case-service-id: true # usa o nome do serviço em minusculo ao invés de maiusculo
