server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhosT:8761/eureka
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # permite q ao invés de usar o localhost do próprio serviço para acessar, usa o próprio api gateway e passa o nome do serviço
          #lower-case-service-id: true # usa o nome do serviço em minusculo ao invés de maiusculo
      routes: # colocar aqui para o swagger pegar
        - id: cambio-service
          uri:  lb://cambio-service
          predicates:
            - Path=/cambio-service/**
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/book-service/**
        - id: openapi
          uri: lb://api-gateway
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs